### ISSUE TITLE
A better ui would be nice, keeping the ui open once they hit exit

### ISSUE THREAD

**Issue by eforce67** [boi1216/BedWars#10]

**Comment by eforce67** [comment]
Ops wrong channel

**Comment by ElectroGamesYT** [comment]
Hi eforce

**Comment by boi1216** [comment]
I can't get it. Can you explain bit more into details? @eforce67

**Comment by eforce67** [comment]
Well the ui keeps closing after buying a product, so maybe keep the ui up for an infinite time while you have an exit button or a back to category button
