### ISSUE TITLE
How do you install the plugin it keeps giving me error codes when trying to install.

### ISSUE THREAD

**Issue by bubbaboi999101** [boi1216/BedWars#13]

**Comment by IceCruelStuff** [comment]
You download the latest build here: https://poggit.pmmp.io/ci/boi1216/BedWars

**Comment by bubbaboi999101** [comment]
How do you add teams and is there a map reset plugin too as well as a scoreboard?

**Comment by IceCruelStuff** [comment]
no idea

**Comment by boi1216** [comment]
Plugin is not ready for use
