### ISSUE TITLE
What are the commands for this?

### ISSUE THREAD

**Issue by enzipenzo** [boi1216/BedWars#19]
I can't seem to find the commands. /bedwars help does nothing, none of any commands related to bedwars do anything.

**Comment by WEATHERCRAFTYT1** [comment]
There is /bedwars create /bedwars generator /bedwars addteam /bedwars position /bedwars setlobby

**Comment by boi1216** [comment]
This repo will not have any further updates
New repo: https://github.com/boi1216/BedWars-Rewrite
