### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by vanysha7d** [boi1216/BedWars#2]
> Server thread/CRITICAL ErrorException: "Undefined offset: 1" (EXCEPTION) in "plugins/BedWars-master (6).phar/src/BedWars/command/DefaultCommand" at line 328
> 
> lugins/BedWars-master (6).phar/src/BedWars/command/DefaultCommand(328): pocketmine\utils\Utils::errorExceptionHandler(integer 8, string[19] Undefined offset: 1, string[111] phar:///plugins/BedWars-master (6).phar/src/Bed, integer 328, array[3])

**Comment by GamakCZ** [comment]
ups

**Comment by BlueWhaleYT** [comment]
The author already said that not yet finish.

**Comment by boi1216** [comment]
Saying crash will not help me to reproduce the issue. When did it happen or what command did you use?

**Comment by eforce67** [comment]
Its simple, but it just happens. I suggest using the command correctly and you won't have a problem. But it rarely happens

**Comment by boi1216** [comment]
I'll be very happy guys if you could tell me when the error occurs so I can push a fix.

**Comment by eforce67** [comment]
$gameName = $args[1]; i found this on 328

**Comment by eforce67** [comment]
$teams = []; foreach($this->teams as $team){ if(count($team->getPlayers()) <= 0 || !$team->hasBed())continue; $players = []; foreach($team->getPlayers() as $player){ if($player->isAlive() && $player->getLevel()->getFolderName() == $this->worldName){ $players[] = $player; } } if(count($players) >= 1){ $teams[] = $team->getName(); } } return $teams;

if(count($team = $this->getAliveTeams()) === 1){ $this->winnerTeam = $team[0]; $this->state = self::STATE_REBOOT; }

Also this could lead to a bug, so i suggest counting the players also if they are alive or the arena will keep going, also the beds will spawn without a team making the players get a free bed kill while this code can leave to counting the teams only and not the rest of the players which restarts the game only.

**Comment by boi1216** [comment]
Fixed in 7129ace

**Comment by boi1216** [comment]
@eforce67 There are only alive players inside of the array, should work fine.
