### ISSUE TITLE
Arena doesn't exist!

### ISSUE THREAD

**Issue by vanysha7d** [boi1216/BedWars#4]
I created an arena, but I can’t enter it, writes there isn’t such an arena, what should I do?
![arena](https://user-images.githubusercontent.com/40440946/75820552-d64eef00-5d9c-11ea-85c3-9a0e18cd05d6.png)

**Comment by vanysha7d** [comment]
`{"name":"arena","minPlayers":2,"playersPerTeam":2,"world":"world","signs":[],"teamInfo":{"red":{"spawnPos":"271.6796:4:236.7913:89.870819091797:20.175109863281","bedPos":"","0":"shopPos","bedPos1":"268:4:240","shopPos":"269.4101:4:237.5493:89.651489257812:20.394393920898","upgradePos":"269.4062:4:235.8244:89.870788574219:20.175109863281"},"blue":{"spawnPos":"271.6772:4:234.4218:280.13650512695:9.4297180175781","bedPos":"","0":"shopPos","bedPos1":"268:4:238","shopPos":"276.1417:4:233.5173:266.32092285156:23.903198242188","upgradePos":"276.1488:4:235.5912:266.32092285156:23.903198242188"}},"generatorInfo":{"arena":[{"type":"iron","position":"274.0267:4:237.6263:","0":"game"},{"type":"gold","position":"273.6768:4:235.9239:","0":"game"},{"type":"diamond","position":"273.7104:4:233.9793:","0":"game"},{"type":"emerald","position":"273.7562:4:231.3922:","0":"game"}]},"lobby":"272.5352:4:244.3235:world","void_y":-1}`

**Comment by eforce67** [comment]
You reload, and then [bedwars] then the arena name on a sign and bang or you may do /bedwars join

**Comment by boi1216** [comment]
With latest commit you can use /bedwars load <game> to initialize the arena without restarting/reloading the server.
