### ISSUE TITLE
I recommend setting              if(count($team = $this->getAliveTeams()) === 1 && count($this->players) <= $playerPerTeam){

### ISSUE THREAD

**Issue by eforce67** [boi1216/BedWars#6]
This could cause a problem if they aren't playing in solo mode of course but it will work differentially so use playerPerTeams since it counts the amount of players on a team and could potentially solve problems like chaos mode or duos. Also count the players if 0 > $playerPerTeam just canceling and switch to the reboot stage ;)

**Comment by boi1216** [comment]
It works fine right now

**Comment by boi1216** [comment]
Fixed in 7dbb6e8
