### ISSUE TITLE
Crash when a player leaves the game during the game

### ISSUE THREAD

**Issue by vanysha7d** [boi1216/BedWars#8]
Error: "Call to a member function getFolderName() on null" (EXCEPTION) in "plugins/BedWars_dev-6.phar/src/BedWars/game/Game" at line 221
04.03 21:41:57 [Server] Server thread/DEBUG #0 plugins/BedWars_dev-6.phar/src/BedWars/game/Game(689): BedWars\game\Game->getAliveTeams()

**Comment by boi1216** [comment]
Fixed in 9654e06
