### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by vanysha7d** [boi1216/BedWars#9]
**Crash when you destroy the bed**

`
ErrorException: "Undefined index: bedPos2" (EXCEPTION) in "plugins/BedWars_dev-7.phar/src/BedWars/game/GameListener" at line 266
05.03 20:52:11 [Server] Server thread/DEBUG #0 plugins/BedWars_dev-7.phar/src/BedWars/game/GameListener(266): pocketmine\utils\Utils::errorExceptionHandler(integer 8, string[24] Undefined index: bedPos2, string[101] phar:///plugins/BedWars_dev-7.phar/src/BedWars/, integer 266, array[11])
`

**The player can leave the game during the countdown and thus the countdown does not stop**
thus one player remains in the arena

`
Error: "Call to a member function getPlayers() on string" (EXCEPTION) in "plugins/BedWars_dev-7.phar/src/BedWars/game/Game" at line 694
05.03 21:01:40 [Server] Server thread/DEBUG #0 plugins/BedWars_dev-7.phar/src/BedWars/game/GameTick(24): BedWars\game\Game->tick()
`

**Comment by vanysha7d** [comment]
**When you write /bedwars setbed**
New version plugin, Dev #8

```
ErrorException: "Undefined offset: 2" (EXCEPTION) in "plugins/BedWars_dev-8.phar/src/BedWars/command/DefaultCommand" at line 287
05.03 22:30:23 [Server] Server thread/DEBUG #0 plugins/BedWars_dev-8.phar/src/BedWars/command/DefaultCommand(287): pocketmine\utils\Utils::errorExceptionHandler(integer 8, string[19] Undefined offset: 2, string[106] phar:///plugins/BedWars_dev-8.phar/src/BedWars/, integer 287, array[7])
```

**Comment by vanysha7d** [comment]
**When you write /bedwars load**
New version plugin, Dev #8

`TypeError: "Argument 1 passed to BedWars\BedWars::validateGame() must be of the type array, object given, called in phar:///plugins/BedWars_dev-8.phar/src/BedWars/BedWars.php on line 155" (EXCEPTION) in "plugins/BedWars_dev-8.phar/src/BedWars/BedWars" at line 166
05.03 22:35:27 [Server] Server thread/DEBUG #0 plugins/BedWars_dev-8.phar/src/BedWars/BedWars(155): BedWars\BedWars->validateGame(object stdClass)`

**Comment by ElectroGamesYT** [comment]
Te dev dont care...
